/**
 * Generator for CSS with Morse code pattern selectors
 */

import { TranslatedMorseRule } from "../types";

/**
 * Generates CSS from translated Morse rules
 *
 * @param translatedRules - The translated Morse rules
 * @returns The generated CSS
 */
export function generateCSS(translatedRules: TranslatedMorseRule[]): string {
  let css = "";

  // Add a header comment
  css += "/* Generated by Morse CSS */\n";
  css += "/* https://github.com/morse-css */\n";
  css += "\n";

  // Generate CSS for each rule
  for (const rule of translatedRules) {
    // Add the selector
    css += `${rule.translatedSelector} {\n`;

    // Add the properties
    for (const [property, value] of Object.entries(rule.properties)) {
      css += `  ${property}: ${value};\n`;
    }

    // Close the rule
    css += "}\n\n";
  }

  return css;
}
