/**
 * Generator for CSS with Morse code pattern selectors
 */

import { TranslatedMorsePattern } from "../types";

/**
 * Generates CSS from translated Morse patterns
 *
 * @param translatedPatterns - The translated Morse patterns
 * @returns The generated CSS
 */
export function generateCSS(translatedPatterns: TranslatedMorsePattern[]): string {
  let css = "";

  // Add a header comment
  css += "/* Generated by Morse CSS */\n";
  css += "/* https://github.com/morse-css */\n";
  css += "\n";

  // Generate CSS for each pattern
  for (const pattern of translatedPatterns) {
    // Add the selector and CSS block
    css += `${pattern.translatedSelector} {\n${pattern.cssBlock}\n}\n\n`;
  }

  return css;
}
